### ISSUE TITLE
Advice for failing 'Ensure permissions are set'

### ISSUE THREAD

**Issue by rromanchuk** [fubarhouse/fubarhouse.npm#53] opened 2017-12-20 18:22 UTC
Most likely user error, but can you point me in the right direction. Standard vanilla aws ubuntu64, remote_user=ubuntu 

TASK [fubarhouse.nodejs : NVM | Ensure permissions are set] *******************************************************************************************************
failed: [web-server] (item=/usr/local/lib/node_modules) => {"changed": false, "failed": true, "item": "/usr/local/lib/node_modules", "msg": "There was an issue creating /usr/local/lib/node_modules as requested: [Errno 13] Permission denied: '/usr/local/lib/node_modules'", "path": "/usr/local/lib/node_modules", "state": "absent"}

**Comment by rromanchuk** [comment] 2017-12-20 18:24
Doesn't this need a `become: yes`?  My user doesn't have permissions for `/usr/local/lib/node_modules`

```
- name: "NVM | Ensure permissions are set"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    owner: "{{ fubarhouse_user }}"
    recurse: no
  with_items:
    - "/usr/local/lib/node_modules"
    - "{{ fubarhouse_user_dir }}/.npm"
    - "{{ fubarhouse_user_dir }}/.nvm"
  changed_when: false
```

**Comment by fubarhouse** [comment] 2017-12-23 10:42
There's a good case for it, so I'll work on this in the next couple of days.

In the interim, you can add the following to this task for the desired effect.

```
become: yes
become_user: "{{ fubarhouse_user }}"
```

**Comment by joestewart** [comment] 2018-01-05 14:49
Hi Karl, thanks for the release but the c53af01 commit is causing issues in vagrant with a fubarhouse_user of "vagrant".

```
TASK [fubarhouse.nodejs : NVM | Ensure permissions are set] ********************
failed: [example_mcdev] (item=/usr/local/lib/node_modules) => {"changed": false, "item": "/usr/local/lib/node_modules", "msg": "There was an issue creating /usr/local/lib/node_modules as requested: [Errno 13] Permission denied: '/usr/local/lib/node_modules'", "path": "/usr/local/lib/node_modules", "state": "absent"}
ok: [example_mcdev] => (item=/home/vagrant/.npm)
ok: [example_mcdev] => (item=/home/vagrant/.nvm)
```

The vagrant user can't write to /usr/local/lib/ at this point.

Removing `become_user: "{{ fubarhouse_user }}"` works for me.

**Comment by fubarhouse** [comment] 2018-01-05 20:11
Yep. I'll mark that as a regression.

@rromanchuk , could you please try substituting the user for root in version 1.8.4?
 
A tag excluding this commit has been released as 1.8.5, and is available via the Galaxy.

**Comment by mhotchen** [comment] 2018-03-03 12:40
I'm currently on 1.8.5 (I think, I installed with ansible-galaxy just now but the ansible-galaxy info command doesn't give a version number, the only hint I have is a link to travis that includes 1.8.5 in it).

I'm having some trouble getting this to work. I'm importing the role from inside my own because I want to create a user to install under first. For convenience I'm currently just testing with the default vagrant user. This is on the vagrant box bento/ubuntu-16.04 (I'm sure you can guess the distro I'm using :P).

First if I try to install as a specific user:

```
- name: Install and configure nodejs, nvm and npm
  import_role: name=fubarhouse.nodejs
  become: yes
  become_user: vagrant
```

This is where it breaks:

```
TASK [fubarhouse.nodejs : NVM | Ensure permissions are set] ********************
failed: [192.168.33.10] (item=/usr/local/lib/node_modules) => {"changed": false, "item": "/usr/local/lib/node_modules", "msg": "There was an issue creating /usr/local/lib/node_modules as requested: [Errno 13] Permission denied: b'/usr/local/lib/node_modules'", "path": "/usr/local/lib/node_modules", "state": "absent"}
ok: [192.168.33.10] => (item=/home/vagrant/.npm)
ok: [192.168.33.10] => (item=/home/vagrant/.nvm)
```

Because the vagrant user of course doesn't have permission to modify `/usr/local/lib`.

Then If I try to run as root:

```
- name: Install and configure nodejs, nvm and npm
  import_role: name=fubarhouse.nodejs
  become: yes
  become_user: root
```

Here is where I get to:

```
TASK [fubarhouse.nodejs : NodeJS | Install all requested versions] *************
failed: [192.168.33.10] (item=0.10.48) => {"changed": true, "cmd": "/usr/local/bin/nvm install 0.10.48", "delta": "0:00:00.002229", "end": "2018-03-03 12:09:21.434866", "item": "0.10.48", "msg": "non-zero return code", "rc": 1, "start": "2018-03-03 12:09:21.432637", "stderr": "/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied", "stderr_lines": ["/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied"], "stdout": "", "stdout_lines": []}
failed: [192.168.33.10] (item=0.10.48) => {"changed": true, "cmd": "/usr/local/bin/nvm install 0.10.48", "delta": "0:00:00.002185", "end": "2018-03-03 12:09:21.950798", "item": "0.10.48", "msg": "non-zero return code", "rc": 1, "start": "2018-03-03 12:09:21.948613", "stderr": "/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied", "stderr_lines": ["/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied"], "stdout": "", "stdout_lines": []}
```

I'm assuming it's dropping down to a regular user at that point (eg. the SSH user, in this case vagrant) despite my efforts to suggest it become root.

If I try installing as vagrant again but with /usr/local/lib/node_modules preconfigured:

```
- name: Create node_modules global directory with correct permissions
  file: path=/usr/local/lib/node_modules owner=vagrant group=vagrant mode=0777 state=directory
```

Then here is where I get to:

```
TASK [fubarhouse.nodejs : NVM | Create an executable] **************************
fatal: [192.168.33.10]: FAILED! => {"changed": false, "checksum": "31e9d754862be4485390df6479b1e8846f664fba", "msg": "Destination /usr/local/bin not writable"}
```

So I modified the undocumented nvm_symlink_exec parameter to a file in vagrant's home directory (~/nvm), try again and get here:

```
TASK [fubarhouse.nodejs : NodeJS | Linking binaries] ***************************
failed: [192.168.33.10] (item=node) => {"changed": false, "item": "node", "msg": "Error while linking: [Errno 13] Permission denied: b'/home/vagrant/.nvm/versions/node/v0.10.48/bin/node' -> b'/usr/local/bin/node'", "path": "/usr/local/bin/node", "state": "absent"}
failed: [192.168.33.10] (item=npm) => {"changed": false, "item": "npm", "msg": "Error while linking: [Errno 13] Permission denied: b'/home/vagrant/.nvm/versions/node/v0.10.48/bin/npm' -> b'/usr/local/bin/npm'", "path": "/usr/local/bin/npm", "state": "absent"}
```

I only want a local installation for a specific user anyway so all of this global stuff is unnecessary for my use case. I've _technically_ got it working at this point by simply ignoring the errors but it's pretty gnarly and means if other parts of the role go wrong I can have some cascading problems. Can it be a flag or something to specify that you want to globally install or not?

**Comment by mhotchen** [comment] 2018-03-03 12:51
Actually it only works as the user I SSH in as (vagrant). I can't create a user then run the role with become_user set to my newly created user (eg. a nodejs user) :(

**Comment by fubarhouse** [comment] 2018-03-04 21:30
@mhotchen, I'll have a better look tonight.

I can't even recall if this role still installs to the specified folder, so it could be safe to remove.

I'll let you know after I've looked into it.

**Comment by fubarhouse** [comment] 2018-03-05 12:24
I believe I've found a solution which should cater for everybody.

I ask that you give it a try, and let me know.
* https://github.com/fubarhouse/ansible-role-nodejs/tree/issue-53

So some problems fixed include:
* Updates the default NVM version
* Updates the default nodejs version
* Prevent root ownership of the IVM clone task
* Removes superseded/unused folder creation tasks
* **Allows root user to create the nvm file (better known as the sym)**
* Updates the badges
* Updates the readme to identify yaml code blocks
* Adds brief documentation for the `nvm_symlink_exec` variable.
* Other very minor changes to the readme.

Please let me know if and how this goes - I'm pretty confident with the results given I haven't messed with this one in some time. I've been putting it off due to legacy support for node 4 on some of my older docker images. So it's been a while, but it appears to be happy again, and tests are beginning to pass as I'm typing this.

**Comment by mhotchen** [comment] 2018-03-05 18:55
Man I hate that about software. You build or configure something and in a couple of months it won't work anymore. I've especially had that problem with ansible. As I'm writing this an update to Ubuntu last night has broken my vagrant box by uninstalling an older version of NFS and the newer version just hangs. Easy enough to fix (although finding a version that works across OSs is going to be a challenge) but it makes me a bit sad that we have to deal with stuff like this.

Anway! Here's a fun one for you, I've checked out your branch and it doesn't work.

Whilst the fubarhouse_user var is set to 'vagrant' the '$HOME' env var is populated with /root :) That produces the following error:

```
TASK [ansible-role-nodejs : NodeJS | Install all requested versions] ***********
failed: [192.168.33.10] (item=0.10.48) => {"changed": true, "cmd": "/usr/local/bin/nvm install 0.10.48", "delta": "0:00:00.002122", "end": "2018-03-05 18:44:50.185998", "item": "0.10.48", "msg": "non-zero return code", "rc": 1, "start": "2018-03-05 18:44:50.183876", "stderr": "/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied", "stderr_lines": ["/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied"], "stdout": "", "stdout_lines": []}
failed: [192.168.33.10] (item=0.10.48) => {"changed": true, "cmd": "/usr/local/bin/nvm install 0.10.48", "delta": "0:00:00.002136", "end": "2018-03-05 18:44:50.690057", "item": "0.10.48", "msg": "non-zero return code", "rc": 1, "start": "2018-03-05 18:44:50.687921", "stderr": "/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied", "stderr_lines": ["/usr/local/bin/nvm: line 4: /root/.nvm/nvm.sh: Permission denied"], "stdout": "", "stdout_lines": []}
```

It's installing in the /root dir, then trying to become the vagrant user when actually executing the install task above. I've added some debug stuff to your branch in a local checkout to demonstrate the problem:

```
TASK [ansible-role-nodejs : ansible_ssh_user] **********************************
ok: [192.168.33.10] => {
    "ansible_ssh_user": "vagrant"
}

TASK [ansible-role-nodejs : ansible_user_id] ***********************************
ok: [192.168.33.10] => {
    "ansible_user_id": "root"
}

TASK [ansible-role-nodejs : fubarhouse_user] ***********************************
ok: [192.168.33.10] => {
    "fubarhouse_user": "vagrant"
}

TASK [ansible-role-nodejs : shell_home_dir] ************************************
ok: [192.168.33.10] => {
    "shell_home_dir": {
        "changed": false, 
        "cmd": "echo $HOME", 
        "delta": "0:00:00.001075", 
        "end": "2018-03-05 18:41:22.904683", 
        "failed": false, 
        "rc": 0, 
        "start": "2018-03-05 18:41:22.903608", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "/root", 
        "stdout_lines": [
            "/root"
        ]
    }
}
```

Swapping the registering of fubarhouse_user from ansible_ssh_user first to ansible_user_id fixes my issues. So now the beginning of main.yml looks like:

```yaml
- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_user_id is defined and fubarhouse_user is not defined

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined and fubarhouse_user is not defined
```

Note that I am connecting with SSH (as the user 'vagrant') but ansible has become root when executing the script hence the change in $HOME and change in ansible_user_id. The above yields the following values for the variables I debugged before:

```
TASK [ansible-role-nodejs : ansible_ssh_user] **********************************
ok: [192.168.33.10] => {
    "ansible_ssh_user": "vagrant"
}

TASK [ansible-role-nodejs : ansible_user_id] ***********************************
ok: [192.168.33.10] => {
    "ansible_user_id": "root"
}

TASK [ansible-role-nodejs : fubarhouse_user] ***********************************
ok: [192.168.33.10] => {
    "fubarhouse_user": "root"
}

TASK [ansible-role-nodejs : shell_home_dir] ************************************
ok: [192.168.33.10] => {
    "shell_home_dir": {
        "changed": false, 
        "cmd": "echo $HOME", 
        "delta": "0:00:00.001256", 
        "end": "2018-03-05 18:46:33.852367", 
        "failed": false, 
        "rc": 0, 
        "start": "2018-03-05 18:46:33.851111", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "/root", 
        "stdout_lines": [
            "/root"
        ]
    }
}
```

At this point the installation is successful! What do you think?

ps. I almost forgot: thanks for being on top of this so quickly. This is for a pet project of mine and your work so far has allowed me to get up and running really quickly.

**Comment by joestewart** [comment] 2018-03-05 19:08
@mhotchen Don't know if it helps until this gets sorted, for vagrant usage we also have these two variables set:

```
fubarhouse_user: vagrant
fubarhouse_user_dir: /home/vagrant
```

**Comment by mhotchen** [comment] 2018-03-05 19:12
Yeah that would work! Although it feels a little like looking in to the internals/implementation details and trusting that they don't change (unless it becomes a documented part of the interface which I would be quite satisfied with as a solution).

**Comment by fubarhouse** [comment] 2018-03-05 19:14
It’s useful that you both are finding this feature troublesome - so I will
have it addressed soon 😊

I appreciate the background work you did to help this one along.

**Comment by mhotchen** [comment] 2018-03-05 19:16
It's the least I can do when I'm depending on your free labour lol. Thanks buddy much appreciated.

**Comment by mhotchen** [comment] 2018-03-06 07:19
Morning fubarhouse.

Unfortunately for me my brain decided to think about ansible instead of sleeping last night and I think I've come up with a pretty simple solution: have a documented variable asking who to install under (eg. fubarhouse_install_user), falling back to ansible_user_id. According to [this superuser answer](https://superuser.com/questions/484277/get-home-directory-by-username) you can get the user's home directory using `~$USER`:

```bash
vagrant@test:~$ pwd ~vagrant
/home/vagrant
vagrant@test:~$ pwd ~root
/home/vagrant
```

So that could be used throughout the script when referencing the installation directory instead of relying on the $HOME variable. A neat trick I didn't know about.

**Comment by fubarhouse** [comment] 2018-03-06 08:58
Good evening!

I'm in Australia, and it's 8pm here. I wasn't aware of that little trick. It doesn't however appear to be working on my laptop. There's always the `$HOME` and `whoami`.

In fact, I've been systematically been removing the mechanism for `fubarhouse_user` and `fubarhouse_user_dir` for some time, however I cannot seem to escape it for this role - so I think I may need to rethink it a little... The goal for me, is to discontinue using the mechanism and any instances of `become`, though the previous commit is a reasonable exemption.

I'll be addressing this tonight, though I may not be able to sit down and focus for another hour or two.

Speak soon.

**Comment by fubarhouse** [comment] 2018-03-06 10:07
I have removed the implementation entirely in favour of the `~` replacement which is supported, however inelegant.

Tests are passing, so you are welcome to test against the changes in branch `issue-53`.

Please let me know - sooner rather than later. I would love to get this released.

**Comment by mhotchen** [comment] 2018-03-07 09:08
Good morning from drizzly and cold England :)

Sorry for the delay I'm dealing with some personal stuff right now. I have tested the latest updates and they work perfectly for me. Really nice work friend and thank you for your promptness. I really appreciate and admire your work.

**Comment by fubarhouse** [comment] 2018-03-07 09:27
@mhotchen,

Thanks, I appreciate your kind words.

I'll organise a release for this tonight - I'm just doing some work on a personal Drupal module I manage.

I'll get to this straight after :)

**Comment by fubarhouse** [comment] 2018-03-07 10:45
Version 1.9 has been released, and Ansible Galaxy has picked the changes up.

This ticket will now be closed - if for any reason it should not be closed, please re-open it.

**Closed as completed by fubarhouse** 2018-03-07 10:45 UTC
